### PR TITLE
Adding locales generation to dockerfile

### PR DESCRIPTION
**Pull request by vsoch**
Locales is needed for correct encoding.

### CODE REVIEW

**Comment by Chilipp** [comment]
hmm, seems not to work. I ran it locally and it seems like it's still using the wrong encoding. So lets fix this with environment variables. Could you please add

```
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
```

to the docker file?

without, `docker run -it --entrypoint python3 -v `pwd`:/github/workspace rseng/pdf-generator -c "import locale; print(locale.getpreferredencoding())"` gives `ANSI_X3.4-1968`, with this settings, we get `UTF-8` and it can read the problematic file.

**Comment by vsoch** [comment]
yep all set! https://github.com/rseng/pdf-generator/pull/7/files#diff-3254677a7917c6c01f55212f86c57fbfR6

**Comment by Chilipp** [comment]
seems to work! thanks @vsoch 

let me know when you made the new release

**Comment by vsoch** [comment]
Sorry for the delay! I had to run and get a flu shot. First time stepping outside in 5 months, wowza.

**Comment by vsoch** [comment]
See https://github.com/rseng/pdf-generator/releases/tag/0.0.4.

**Pull request merged**
